FROM ubuntu:trusty

RUN sed -i -E 's/(archive|security).ubuntu.com/192.168.1.142/' /etc/apt/sources.list && \
    sed -i -E 's/^deb-src/# deb-src/' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y dpkg-dev debhelper build-essential sudo wget curl

RUN useradd builder && \
    install -d /build -o builder -g builder

ADD scripts/bootstrap.sh /bootstrap.sh
ADD scripts/build.sh /build.sh

ENTRYPOINT ["/bootstrap.sh"]
